{% set name = "langchain-mistralai" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_mistralai-{{ version }}.tar.gz
  sha256: d68fc348daeb6d2eac5862575e65b20c4f5087344c4695a30be89d69a31fd934

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - pydantic >=2.0.0,<3.0.0
    - python >={{ python_min }},<4.0
    - langchain-core >=1.0.0,<2.0.0
    - tokenizers >=0.15.1,<1.0.0
    - httpx >=0.25.2,<1.0.0
    - httpx-sse >=0.3.1,<1.0.0

test:
  imports:
    - langchain_mistralai
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Mistral and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
