{% set name = "langchain-mistralai" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_mistralai-{{ version }}.tar.gz
  sha256: fbeee35d559999fb28fd831683602706b6ba49a4ee5235d4e292dce01f40a700

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - pydantic <3,>=2
    - python >={{ python_min }},<4.0
    - langchain-core <1.0.0,>=0.3.45
    - tokenizers <1,>=0.15.1
    - httpx <1,>=0.25.2
    - httpx-sse <1,>=0.3.1

test:
  imports:
    - langchain_mistralai
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Mistral and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
