schema_version: 1

context:
  name: langchain-mistralai
  version: "1.1.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/langchain_mistralai-${{ version }}.tar.gz
  sha256: 3c852b1b2d8a729299f25fba7d5c9cadb9e2128387c2771745e8e8cb412b33cd

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - pydantic >=2.0.0,<3.0.0
    - python >=${{ python_min }},<4.0
    - langchain-core >=1.2.19,<2.0.0
    - tokenizers >=0.15.1,<1.0.0
    - httpx >=0.25.2,<1.0.0
    - httpx-sse >=0.3.1,<1.0.0

tests:
  - python:
      imports:
        - langchain_mistralai
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: An integration package connecting Mistral and LangChain
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/langchain-ai/langchain

extra:
  recipe-maintainers:
    - jan-janssen
